# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  HEROKU_APP_NAME: ${{ 'timezone-api-01' }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  build_deploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout project
      uses: actions/checkout@v2
    
    - name: set up python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi
    
    - name: lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: check unit tests and coverage
      run: |
        export PYTHONPATH=app
        pytest --cov-fail-under=90 --cov=app tests/

    - name: deploy to heroku
      run: |
        heroku container:login
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $HEROKU_APP_NAME
        heroku container:release web -a $HEROKU_APP_NAME